# Generated by Django 3.2.2 on 2021-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='excluding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='query',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queries',
            name='required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
