# Generated by Django 3.2.2 on 2021-05-14 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
