# Generated by Django 3.2.2 on 2021-05-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_queries_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='date',
        ),
    ]
